sc_verify_multishop_index:
  path: /verify-multishop
  methods: [GET]
  defaults:
    _controller: 'sc_verify_multishop.controller.diagnostic::indexAction'
    _legacy_controller: AdminScVerifyMultishop
    _legacy_link: AdminScVerifyMultishop
